# Sets user-defined palette
palette = "rose-pine"

# Pure Preset
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "iris"

[character]
success_symbol = "[â¯](gold)"
error_symbol = "[â¯](love)"
vimcmd_symbol = "[â®](pine)"

[git_branch]
format = "[$branch]($style)"
style = "higlight-med"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "foam"
conflicted = "â€‹"
untracked = "â€‹"
modified = "â€‹"
staged = "â€‹"
renamed = "â€‹"
deleted = "â€‹"
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "highlight-med"

[cmd_duration]
format = "[$duration]($style) "
style = "gold"

[python]
format = "[$virtualenv]($style) "
style = "highlight-med"
# End Pure Preset

# No Nerd Font Fix
# [battery]
# full_symbol = "â€¢ "
# charging_symbol = "â‡¡ "
# discharging_symbol = "â‡£ "
# unknown_symbol = "â“ "
# empty_symbol = "â— "
#
# [erlang]
# symbol = "â“” "
#
# [nodejs]
# symbol = "[â¬¢](bold pine) "
#
# [pulumi]
# symbol = "ğŸ§Š "
# End No Nerd Font Fix

[palettes.rose-pine]

base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight-low = "#21202e"
highlight-med = "#403d52"
highlight-high = "#524f67"
